---
title: "FINAL"
author: "Prathit Shukla"
date: "11/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
NBA = read.csv("mvp_votings.csv",header=TRUE)

#NBA


#----- we want to remove duplicate predictors and ones that are correleated with winshare at all, can do this through explanatory plots, and cross-correleation measures
#pairs(NBA[,c(2,3,5,6,12,13)])

#pairs(NBA[,c(17,18,19,20,21,22,26,27)])

#pairs(NBA[,c(6,8,11,12,13,15,18,19)])
#pairs(NBA[,c(2,14,17,21)])


# some varibales just by there names we can get rid of like offensive rebound, defnsive rebound for just total rebounds. 
# also with these correleation we unsurprisinly see that with minutes played all the other stats are highly correleated together such as points, reb, assits as increase obviously as these players play more.

#But it still might be worth it to keep

# Now we can do pairs again with the points we want to keep

#pairs(NBA[,c(2,3,5,6,17,18,19,20,21,22,26)])


# important to note in report lot of NBA research standardizes all stats to per 48 equivlent but here we want to keep the totals ???? or not




pairs(NBA[,c(5,6,17,18,19,20,21,22,26)])

#fga is not relevent as is highly correlated with others
#15 - is award share or what we want to predict with our regression model
NBAsub = data.frame(NBA[,c(5,6,15,17,18,19,20,21,22,26)])
smp_size <- floor(0.75 * nrow(NBAsub))
set.seed(123)

train_ind <- sample(seq_len(nrow(NBAsub)), size = smp_size)

train <- NBAsub[train_ind, ]
test <- NBAsub[-train_ind, ]


initialLM = lm(award_share ~ . ,data=train)
summary(initialLM)

```

